apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: parking
spec:
  selector:
    app: billing
  type: NodePort
  ports:
  - port: 3003
    targetPort: 3003
    nodePort: 32003
