apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-deployment
  namespace: parking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
      - name: reservation
        image: reservation:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3002
